from pydantic import BaseModel, Field
from datetime import datetime
from typing import Any, Dict, Optional

class SensorReading(BaseModel):
    """Base model for any sensor reading generated by a VirtualDevice."""
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Time of the reading")
    device_id: str = Field(..., description="Unique identifier for the device instance")
    preset: str = Field(..., description="The type of device (e.g., IndustrialMotor)")
    anomaly: int = Field(default=0, description="1 if an anomaly is currently active, 0 otherwise")
    anomaly_type: Optional[str] = Field(default=None, description="The type of active anomaly, if any")
    sensors: Dict[str, float] = Field(..., description="Key-value pairs of sensor names to their current readings")
